import { askLLMForJson } from "./llm.service";
import { makeIdGenerator } from "../utils/idGen";
import { CrawledPage, Requirement, Question, Flashcard, CompanyBrief, QuestionCategory } from "../types/kit.types";

// ---------- Company brief ----------

interface RawBrief {
  summary: string;
  what_they_do: string;
}

export async function generateCompanyBrief(
  companyName: string,
  companyPages: CrawledPage[]
): Promise<CompanyBrief> {
  if (companyPages.length === 0) {
    return {
      summary: `No usable public information could be retrieved about ${companyName || "this company"}. This brief could not be generated from real sources.`,
      what_they_do: "Unknown - the company site could not be crawled successfully.",
      sources: [],
    };
  }

  const combined = companyPages.map((p) => `URL: ${p.url}\nTITLE: ${p.title}\n${p.text}`).join("\n\n---\n\n").slice(0, 12_000);
  const system =
    `You write short, factual company briefs for interview candidates, based only on the provided page text. ` +
    `Never invent facts, funding details, or numbers that are not present in the text. ` +
    `Respond with ONLY JSON: { "summary": string, "what_they_do": string }. Keep each field to 2-4 sentences.`;

  const raw = await askLLMForJson<RawBrief>(
    `Company: ${companyName}\n\nPage content:\n${combined}`,
    system
  );

  return {
    summary: raw.summary,
    what_they_do: raw.what_they_do,
    sources: companyPages.map((p) => p.url),
  };
}

// ---------- Question generation ----------

interface RawQuestion {
  requirement_id: string;
  prompt: string;
  answer_outline: string;
  difficulty: 1 | 2 | 3;
}

const CATEGORY_INSTRUCTIONS: Record<QuestionCategory, string> = {
  technical: "Write hands-on technical questions that test real, practical knowledge of the specific technology or skill named in each requirement (not generic trivia).",
  behavioural: "Write behavioural questions (e.g. STAR-format) that probe how the candidate has actually handled situations related to each requirement, such as leadership, mentoring, or conflict.",
  "system-design": "Write system-design / architecture questions appropriate to the seniority implied by each requirement.",
  "company-fit": "Write questions that probe whether the candidate's experience and motivations align with this specific company and role, using the requirement as the anchor.",
};

// Generates questions for one bucket of requirements that share a
// category. This is intentionally called once per category (technical,
// behavioural, ...) with different instructions and a different requirement
// set each time, per the brief: a "5+ years React" requirement and a
// "mentors junior engineers" requirement should not be generated by the
// same call with the same instructions.
export async function generateQuestionsForCategory(
  requirements: Requirement[],
  category: QuestionCategory,
  hiringSignalSummary: string
): Promise<Question[]> {
  if (requirements.length === 0) return [];

  const reqList = requirements.map((r) => `- id: ${r.id} | ${r.priority.toUpperCase()} | ${r.text}`).join("\n");
  const system =
    `You generate interview questions for a candidate preparing for a real interview.\n` +
    CATEGORY_INSTRUCTIONS[category] +
    `\nWhat is known about this company's actual interview process: ${hiringSignalSummary}\n` +
    `Generate 1-2 questions PER requirement listed. Each question must include the id(s) of the requirement(s) it covers.\n` +
    `Respond with ONLY JSON: { "questions": [ { "requirement_id": string, "prompt": string, "answer_outline": string, "difficulty": 1|2|3 } ] }`;

  const raw = await askLLMForJson<{ questions: RawQuestion[] }>(
    `Requirements:\n${reqList}`,
    system
  );

  const nextId = makeIdGenerator("q");
  return (raw.questions || [])
    .filter((q) => q.prompt && requirements.some((r) => r.id === q.requirement_id))
    .map((q) => ({
      id: nextId(),
      requirement_ids: [q.requirement_id],
      category,
      prompt: q.prompt.trim(),
      answer_outline: (q.answer_outline || "").trim(),
      difficulty: [1, 2, 3].includes(q.difficulty) ? q.difficulty : 2,
    }));
}

// Maps a requirement's "kind" to the question category it should
// generate. Domain requirements produce company-fit questions since
// they're usually about domain/product alignment rather than raw
// engineering skill.
export function categoryForKind(kind: Requirement["kind"]): QuestionCategory {
  if (kind === "behavioural") return "behavioural";
  if (kind === "domain") return "company-fit";
  return "technical";
}

// ---------- Flashcards ----------

interface RawFlashcard {
  requirement_id: string;
  front: string;
  back: string;
}

export async function generateFlashcards(requirements: Requirement[]): Promise<Flashcard[]> {
  if (requirements.length === 0) return [];

  const reqList = requirements.map((r) => `- id: ${r.id} | ${r.text}`).join("\n");
  const system =
    `Create one concise flashcard per requirement to help a candidate revise. ` +
    `"front" is a short question or prompt, "back" is a concise, correct answer or key points. ` +
    `Respond with ONLY JSON: { "flashcards": [ { "requirement_id": string, "front": string, "back": string } ] }`;

  const raw = await askLLMForJson<{ flashcards: RawFlashcard[] }>(`Requirements:\n${reqList}`, system);

  const nextId = makeIdGenerator("f");
  return (raw.flashcards || [])
    .filter((f) => f.front && f.back && requirements.some((r) => r.id === f.requirement_id))
    .map((f) => ({
      id: nextId(),
      front: f.front.trim(),
      back: f.back.trim(),
      requirement_ids: [f.requirement_id],
    }));
}
